spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/crest_device_simulator"
    username: "postgres"
    password: "1234"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

simulator:
  config:
    sleepDuration: 30S
    # Uri of the target coap server
    uri: coaps://localhost:55684/sng
