#SPDX-FileCopyrightText: Contributors to the GXF project
#
#SPDX-License-Identifier: Apache-2.0
simulator:
  config:
    scheduled-message: "classpath:messages/kod-alarm-message.json"
    success-message: "classpath:messages/psk-change-success-message.json"
    failure-message: "classpath:messages/psk-change-failure-message.json"
    # Simulator will produce valid/invalid CBOR messages
    produce-valid-cbor: true
    # pre-shared key for coaps (dtls)
    #    pskIdentity: coap_simulator
    #    pskKey: coaps_secret_key
    psk-identity: 867787050253370
    psk-key: ABCDEFGHIJKLMNOP
    psk-secret: "123456"
    cipher-suite: TLS_PSK_WITH_AES_128_GCM_SHA256
