spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/crest_device_simulator"
    username: "postgres"
    password: "1234"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

simulator:
  config:
    message-path: "messages/kod-alarm-message.json"
    # Simulator will produce valid/invalid CBOR messages
    produce-valid-cbor: true
    # Uri of the target coap server
    uri: coaps://localhost:55684/sng
    # pre-shared key for coaps (dtls)
    #    pskIdentity: coap_simulator
    #    pskKey: coaps_secret_key
    psk-identity: 867787050253370
    psk-key: ABCDEFGHIJKLMNOP
