#SPDX-FileCopyrightText: Contributors to the GXF project
#
#SPDX-License-Identifier: Apache-2.0
simulator:
  config:
    # Simulator will produce valid/invalid CBOR messages
    produce-valid-cbor: true
    # pre-shared key for coaps (dtls)
    #    pskIdentity: coap_simulator
    #    pskKey: coaps_secret_key
    psk-identity: 867787050253370
    psk-key: ABCDEFGHIJKLMNOP
    psk-secret: "123456"
