
simulator:
  config:
    scheduled-message-path: "messages/kod-alarm-message.json"
    success-message-path: "messages/kod-alarm-message.json"
    failure-message-path: "messages/kod-alarm-message.json"
    # Simulator will produce valid/invalid CBOR messages
    produce-valid-cbor: true
    # pre-shared key for coaps (dtls)
    #    pskIdentity: coap_simulator
    #    pskKey: coaps_secret_key
    psk-identity: 867787050253370
    psk-key: ABCDEFGHIJKLMNOP
    psk-secret: "123456"
