spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

simulator:
  config:
    message-path: "messages/kod-message.json"
    # Simulator will produce valid/invalid CBOR messages
    produce-valid-cbor: true
    # flag used for switching between local and remote testing
    local-testing: true
    # flag used for switching between coap and coaps (dtls)
    use-dtls: false
    # port used for coap
    port: 55683
    # port used for coaps (dtls)
    dtls-port: 55684
    # host used for local testing
    local-host: localhost
    # host used for remote testing
    remote-host: 18.184.44.224
    # coap resource path
    path: "coap-path"
    # pre-shared key for coaps (dtls)
    #    pskIdentity: coap_simulator
    #    pskKey: coaps_secret_key
    psk-identity: 867787050253370
    psk-key: ABCDEFGHIJKLMNOP
