#SPDX-FileCopyrightText: Contributors to the GXF project
#
#SPDX-License-Identifier: Apache-2.0
spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

simulator:
  config:
    scheduled-message: "classpath:messages/kod-message.json"
    success-message: "classpath:messages/psk-change-success-message.json"
    failure-message: "classpath:messages/psk-change-failure-message.json"
    # Simulator will produce valid/invalid CBOR messages
    produce-valid-cbor: true
    # Uri of the target coap server
    uri: coap://localhost:55684/coap-path
    # pre-shared key for coaps (dtls)
    #    pskIdentity: coap_simulator
    #    pskKey: coaps_secret_key
    psk-identity: 867787050253370
    psk-key: ABCDEFGHIJKLMNOP
    psk-secret: "123456"
    sleep-duration: 100ms
    cipher-suites: TLS_PSK_WITH_AES_128_GCM_SHA256
